name: Terraform Release

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: "AWS Access Key ID from Vocareum"
        required: true
      aws_secret_access_key:
        description: "AWS Secret Access Key from Vocareum"
        required: true
      aws_session_token:
        description: "AWS Session Token from Vocareum"
        required: true
      aws_region:
        description: "AWS Region"
        required: true
        default: "us-east-1"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: iac

    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      AWS_SESSION_TOKEN: ${{ inputs.aws_session_token }}
      AWS_DEFAULT_REGION: ${{ inputs.aws_region }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve